apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: favouritemovies
  name: favouritemovies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favouritemovies
  template:
    metadata:
      labels:
        app: favouritemovies
    spec:
      containers:
      - image: sharanggupta/favouritemovies
        name: favouritemovies
