apiVersion: v1
kind: Service
metadata:
  labels:
    app: favouritemovies
  name: favouritemovies
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodeport: 30000
  selector:
    app: favouritemovies